apiVersion: apps/v1
kind: Deployment
metadata:
  name: followup-deployment
  labels:
    app: followup-deployment
spec:
  selector:
    matchLabels:
      app: followup-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: followup-deployment
    spec:
      containers:
      - name: followup-service
        image: braulinho/followup-service:latest 
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-service:8081
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-service:8761
        - name: eureka.instance.preferIpAddress
          value: "true"
        
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: followup
              key: host
              
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: followup
              key: name
              
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
              
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
              
        - name: DB_PORT
          value: "5432"
        
---
apiVersion: v1
kind: Service
metadata:
  name: followup-service
  labels:
    app: followup-service
spec:
  selector:
    app: followup-deployment
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP
