apiVersion: v1
kind: Service
metadata:
  name: postgres-loan
  labels:
    app: postgres-loan
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-loan
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-loan
  labels:
    app: postgres-loan
spec:
  selector:
    matchLabels:
      app: postgres-loan
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-loan
    spec:
      containers:
      - image: postgres:latest
        name: postgres-loan
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
              
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: loan
              key: name      
  
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-credentials
              key: username 

        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage-loan
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-persistent-storage-loan
        persistentVolumeClaim:
          claimName: postgres-pv-claim-loan
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim-loan
  labels:
    app: postgres-loan
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

