apiVersion: v1
kind: Service
metadata:
  name: postgres-simulate
  labels:
    app: postgres-simulate
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-simulate
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-simulate
  labels:
    app: postgres-simulate
spec:
  selector:
    matchLabels:
      app: postgres-simulate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-simulate
    spec:
      containers:
      - image: postgres:latest
        name: postgres-simulate
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-db
              key: simulate-db-name
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-simulate-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-simulate-pv-claim
  labels:
    app: postgres-simulate
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-simulate-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/postgres/simulate
  storageClassName: standard
