apiVersion: v1
kind: Service
metadata:
  name: postgres-register
  labels:
    app: postgres-register
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-register
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-register
  labels:
    app: postgres-register
spec:
  selector:
    matchLabels:
      app: postgres-register
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-register
    spec:
      containers:
      - image: postgres:latest
        name: postgres-register
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
              
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: register
              key: name      
  
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username

        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage-register
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-persistent-storage-register
        persistentVolumeClaim:
          claimName: postgres-pv-claim-register
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim-register
  labels:
    app: postgres-register
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

