apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
              
        - name: POSTGRES_DB
          value: "postgres"
          
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username

        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
          
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
          
          
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
          
      - name: init-scripts
        configMap:
          name: postgres-init-scripts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init-db.sh: |
    #!/bin/bash
    set -e

    # Crear las bases de datos si no existen
    psql -U "$POSTGRES_USER" <<-EOSQL
      DO \$\$ 
      BEGIN
        IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'register') THEN
          CREATE DATABASE register;
        END IF;
      END
      \$\$;

      DO \$\$ 
      BEGIN
        IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'loan') THEN
          CREATE DATABASE loan;
        END IF;
      END
      \$\$;
    EOSQL

