apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulate-service
  labels:
    app: simulate-service
spec:
  selector:
    matchLabels:
      app: simulate-service
  replicas: 1
  template:
    metadata:
      labels:
        app: simulate-service
    spec:
      containers:
      - name: simulate-service
        image: braulinho/simulate-service:latest  # Nombre de la imagen del microservicio
        ports:
        - containerPort: 8002  # Puerto interno del contenedor
---
apiVersion: v1
kind: Service
metadata:
  name: simulate-service
  labels:
    app: simulate-service
spec:
  selector:
    app: simulate-service
  ports:
    - port: 8010  # Puerto expuesto dentro del servicio
      targetPort: 8002  # Puerto del contenedor
  type: ClusterIP  # Tipo ClusterIP para acceso interno

