server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: register-service
          uri: http://register-service
          predicates:
            - Path=/register/**
            
        - id: loan-service
          uri: http://loan-service
          predicates:
            - Path=/loans/**

        - id: document-service
          uri: http://document-service
          predicates:
            - Path=/documents/**
            
        - id: simulate-service
          uri: http://simulate-service
          predicates:
            - Path=/simulate/**
            
        - id: evaluation-service
          uri: http://evaluation-service
          predicates:
            - Path=/evaluate/**
            
        - id: followup-service
          uri: http://followup-service
          predicates:
            - Path=/followup/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS 
            allowedHeaders:
              - "*"

