server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service.default.svc.cluster.local:8761/eureka
  instance:
    hostname: gateway-service

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: register-service
          uri: lb://register-service
          predicates:
            - Path=/register/**
            
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loans/**

        - id: document-service
          uri: lb://loan-service
          predicates:
            - Path=/documents/**
            
        - id: simulate-service
          uri: lb://simulate-service
          predicates:
            - Path=/simulate/**
            
        - id: evaluation-service
          uri: lb://evaluation-service
          predicates:
            - Path=/evaluate/**
            
        - id: followup-service
          uri: lb://followup-service
          predicates:
            - Path=/followup/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS 
            allowedHeaders:
              - "*"

